# SPDX-FileCopyrightText: 2019-2021 Vishesh Handa <me@vhanda.in>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    fixme: ignore
    hack: ignore
    directives_ordering: ignore
  exclude:
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"
    - lib/account/init.dart
    - lib/experiments/**

linter:
  rules:
    constant_identifier_names: false
    avoid_renaming_method_parameters: false
    use_key_in_widget_constructors: false
    prefer_function_declarations_over_variables: false
    no_logic_in_create_state: false
    non_constant_identifier_names: false
    use_string_buffers: true
    avoid_void_async: true
    # unawaited_futures: true
    no_leading_underscores_for_local_identifiers: false
    library_private_types_in_public_api: false
    use_build_context_synchronously: false
    dangling_library_doc_comments: false
